//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTwinPatientWPF.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthMetric
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public int MetricTypeId { get; set; }
        public decimal Value { get; set; }
        public System.DateTime MeasuredAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual MetricType MetricType { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
