//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTwinPatientWPF.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalCard
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public int BloodTypeId { get; set; }
        public int Height { get; set; }
        public decimal Weight { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual BloodType BloodType { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
