//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTwinPatientWPF.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DigitalTwinPatientDBTestOneEntities : DbContext
    {
        public DigitalTwinPatientDBTestOneEntities()
            : base("name=DigitalTwinPatientDBTestOneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<BloodType> BloodType { get; set; }
        public virtual DbSet<Consultaion> Consultaion { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Diagnosis> Diagnosis { get; set; }
        public virtual DbSet<DiagnosisCategory> DiagnosisCategory { get; set; }
        public virtual DbSet<DiagnosisStatus> DiagnosisStatus { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<DoseUnit> DoseUnit { get; set; }
        public virtual DbSet<Frequence> Frequence { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<HealthMetric> HealthMetric { get; set; }
        public virtual DbSet<Instruction> Instruction { get; set; }
        public virtual DbSet<MedicalCard> MedicalCard { get; set; }
        public virtual DbSet<Medication> Medication { get; set; }
        public virtual DbSet<MetricType> MetricType { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<PatientCompaint> PatientCompaint { get; set; }
        public virtual DbSet<PatientHistory> PatientHistory { get; set; }
        public virtual DbSet<Prescription> Prescription { get; set; }
        public virtual DbSet<PrescriptionArchive> PrescriptionArchive { get; set; }
        public virtual DbSet<PrescriptionStatus> PrescriptionStatus { get; set; }
        public virtual DbSet<Severity> Severity { get; set; }
        public virtual DbSet<Specialization> Specialization { get; set; }
        public virtual DbSet<Symptom> Symptom { get; set; }
        public virtual DbSet<SymptomCategory> SymptomCategory { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UnitOfMetricType> UnitOfMetricType { get; set; }
        public virtual DbSet<WellnessJournal> WellnessJournal { get; set; }
    }
}
