//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTwinPatientWPF.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientComplaint
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public int SymptomId { get; set; }
        public System.DateTime ComplaintDate { get; set; }
        public int SeverityId { get; set; }
        public string Description { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Severity Severity { get; set; }
        public virtual Symptom Symptom { get; set; }
    }
}
