//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTwinPatientWPF.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public int DoctorId { get; set; }
        public int MedicationId { get; set; }
        public int Quantity { get; set; }
        public int DoseUnitId { get; set; }
        public int FrequenceId { get; set; }
        public int DurationInDay { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int InstructionId { get; set; }
        public int PrescriptionStatusId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual DoseUnit DoseUnit { get; set; }
        public virtual Frequence Frequence { get; set; }
        public virtual Instruction Instruction { get; set; }
        public virtual Medication Medication { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual PrescriptionStatus PrescriptionStatus { get; set; }
    }
}
