//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTwinPatientWPF.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellnessJournal
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> MoodScore { get; set; }
        public string Notes { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
